# Generated by Django 5.1.2 on 2024-10-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Age', models.IntegerField(default='', max_length=50)),
                ('Contact', models.IntegerField(default='', max_length=50)),
                ('Mail', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
